### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by mayusee** [mayusee/chat-space#11]
＃IPアドレス
3.114.95.202

**Comment by kohei-isoda** [comment]
田中さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◯ メッセージ投稿画面に余白が出来てしまっている
[![Screenshot from Gyazo](https://gyazo.com/0c860b60b9d1273667b4f5cbc1822e30/raw)](https://gyazo.com/0c860b60b9d1273667b4f5cbc1822e30)

逆に言えばこれ以外はとても綺麗に作られていました、あともう少しです！
修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mayusee** [comment]
いそださん、レビューありがとうございました。
私の方では余白が確認できなかったのですが、form-areaのpaddingを変えてみました。
こちらでいかがでしょうか？

**Comment by chiii220** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by mayusee** [comment]
ありがとうございました！！
